### ISSUE TITLE
airbnb.Api method stopped working when providing email/password

### ISSUE THREAD

**Issue by eladhayun-rep-holdings** [nderkach/airbnb-python#25]
```
import airbnb
api = airbnb.Api("some@email.com", "password")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/eladh/Development/yalarent/yalarent-airbnb-connector/.venv/lib/python3.9/site-packages/airbnb/api.py", line 142, in __init__
    raise VerificationError
airbnb.api.VerificationError
```

**Comment by remybar** [comment]
Have you tried that ? https://github.com/nderkach/airbnb-python#-verificationerror-420

**Comment by eladhayun-rep-holdings** [comment]
@remybar thanks for your reply, yes generally in my code i'm reusing the token:

```
airbnb_api.login(
        airbnb_access_token=airbnb_access_token, proxy_servers=load_proxiy_list()
    )
```

**Comment by eladhayun-rep-holdings** [comment]
its just that the details api stopped working, (someone opened a ticket about it yesterday and closed it) he sayed a new token needs to be retreived so i tried that...

**Comment by kingfisher429** [comment]
Is there a work around? Is so could someone please explain it.

**Comment by jbertscher** [comment]
Check out the [related issue raised earlier](https://github.com/nderkach/airbnb-python/issues/24).
